#!name=Sửa định vị Apple WLOC
#!desc=Sửa toạ độ trả về từ dịch vụ định vị mạng của Apple | Shortcuts (khuyên dùng): Đặt vị trí WLOC https://www.icloud.com/shortcuts/ea9629bfaf0744e1990d07494bc36d5a Khôi phục WLOC https://www.icloud.com/shortcuts/38f9c92948564e89b56f39c4f7ca52ea | Trang chọn điểm: https://build-4sl.pages.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/2KGT/build/tree/main/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/2KGT/build/refs/heads/main/wloc/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/2KGT/build/refs/heads/main/wloc/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
