#!name=Sửa định vị Apple WLOC
#!desc=Sửa toạ độ trả về từ dịch vụ định vị mạng của Apple (Shadowrocket - Tiểu Hoả Tiễn) | Shortcuts (khuyên dùng): Đặt vị trí WLOC https://www.icloud.com/shortcuts/ea9629bfaf0744e1990d07494bc36d5a Khôi phục WLOC https://www.icloud.com/shortcuts/38f9c92948564e89b56f39c4f7ca52ea | Trang chọn điểm: https://build-4sl.pages.dev/
#!author=Yu9191 Rewrite
#!homepage=https://github.com/2KGT/build/tree/main/wloc
#!icon=https://raw.githubusercontent.com/2KGT/build/refs/heads/main/wloc/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/2KGT/build/refs/heads/main/wloc/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/2KGT/build/refs/heads/main/wloc/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
